name: Pre-merge checks

on:
  - pull_request

jobs:
  check_labels:
    name: Check required labels
    runs-on: ubuntu-latest

    steps:
      - name: Check required labels
        uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  docs_and_versions:
    name: Update docs and versions
    runs-on: ubuntu-latest
    needs:
      - check_labels

    steps:
      - name: Fix .git owner
        run: if test -d .git; then sudo chown ubuntu:ubuntu -R .git; fi

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1.4.0"
        with:
          fallback: 0.0.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get next version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Update cloud_module tag major version
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: sh ${GITHUB_WORKSPACE}/.github/scripts/set_cloud_module_tag.sh -p "${GITHUB_WORKSPACE}" -v "${{ steps.semvers.outputs.major }}"

      - name: Update cloud_module tag minor version
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: sh ${GITHUB_WORKSPACE}/.github/scripts/set_cloud_module_tag.sh -p "${GITHUB_WORKSPACE}" -v "${{ steps.semvers.outputs.minor }}"

      - name: Update cloud_module tag patch version
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: sh ${GITHUB_WORKSPACE}/.github/scripts/set_cloud_module_tag.sh -p "${GITHUB_WORKSPACE}" -v "${{ steps.semvers.outputs.patch }}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Run terraform fmt
        id: fmt
        run: terraform fmt -diff -recursive

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          config-file: .github/config/terraform-docs.yaml

      - name: Fix .git owner
        run: "" #sudo chown ubuntu:ubuntu -R .git

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Workflow updates"

  validate_and_lint:
    name: Run terraform validate and TFLint
    runs-on: ubuntu-latest
    needs:
      - check_labels
      - docs_and_versions

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: bendrucker/terraform-configuration-aliases-action@v1

      - name: Run terraform init
        run: terraform init

      - name: Run terraform validate
        run: terraform validate

      - name: Run TFLint
        uses: reviewdog/action-tflint@v1.22.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tflint_version: "v0.49.0"
          filter_mode: nofilter
          tflint_init: true
          fail_on_error: false
          flags: "--module --recursive"
